name: Submit Python Module
description: Submit a new Python code module to Sifzz
title: "[MODULE] "
labels: ["Module Request"]
body:
  - type: markdown
    attributes:
      value: |
        ## Module Submission
        Thank you for submitting a module to Sifzz! Please fill out all required fields below.

  - type: input
    id: module-name
    attributes:
      label: Module Name
      description: The name of your module (as it will appear in Sifzz)
      placeholder: e.g., data_processor
    validations:
      required: true

  - type: input
    id: module-filename
    attributes:
      label: Module Filename
      description: The filename of your Python module. Preferably in camelCase.
      placeholder: e.g., myModule.py
    validations:
      required: true

  - type: textarea
    id: module-description
    attributes:
      label: Module Description
      description: Describe what your module does and its main features
      placeholder: Provide a clear and concise description of your module's functionality
    validations:
      required: true

  - type: textarea
    id: module-code
    attributes:
      label: Module Code
      description: Paste your complete Python module code here
      placeholder: |
        # Your Python code here
        import sys
        import os
        
        # Add the parent directory to sys.path so we can import sifzz
        parent_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        if parent_d......
        import re
      render: python
    validations:
      required: true

  - type: checkboxes
    id: submission-checklist
    attributes:
      label: Submission Checklist
      description: You must agree to all of the following before submitting
      options:
        - label: I agree that my module is suitable for publishing and has been tested
          required: true
        - label: I agree that my module is safe and has no malware/viruses
          required: true
        - label: This is not a re-upload
          required: true
        - label: I have reviewed my code with the Module Development Guide (MDG)
          required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other information you'd like to provide (dependencies, usage examples, etc.)
      placeholder: Optional additional context
    validations:
      required: false
